version: '3.8'

services:
  jungle:
#    image: jungle_devs_test_001_jungle
    build: .
    container_name: jungle
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - postgresql

  postgresql:
    container_name: postgresql
    image: postgres
    environment:
      POSTGRES_PASSWORD: "jungle123"
      POSTGRES_USER: "jungle"
      POSTGRES_DB: "jungle"
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5671:5672"

  celery:
    container_name: celery
    build: .
    command: celery -A project worker -l INFO
    volumes:
      - .:/usr/src/app
    environment:
      - CELERY_BROKER=amqp://guest@rabbitmq//
      - CELERY_BACKEND=redis://redis:6379/0


  flower:
    container_name: flower
    build: .
    command: celery $app $tasks flower
    ports:
      - "5556:5555"
    environment:
      - CELERY_BROKER=amqp://guest@rabbitmq//
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - rabbitmq
      - celery

  celery_beat:
    container_name: celery_beat
    build: .
    command: celery -A project beat -l INFO
    environment:
      - CELERY_BROKER=amqp://guest@rabbitmq//
      - CELERY_BACKEND=redis://redis:6379/0
    volumes:
      - .:/usr/src/app
    depends_on:
      - rabbitmq
      - celery
      - redis

  redis:
    container_name: redis
    image: 'redis:alpine'

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    volumes:
      - .:/usr/src/app
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: "single-node"

volumes:
  postgresql_data: