version: '3.8'

services:
  jungle:
    build: .
    container_name: jungle
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - postgresql

  postgresql:
    container_name: postgresql
    hostname: postgresql
    image: postgres
    environment:
      POSTGRES_PASSWORD: "jungle123"
      POSTGRES_USER: "jungle"
      POSTGRES_DB: "jungle"
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data

volumes:
  postgresql_data: