version: '3.8'

services:
  postgresql:
    container_name: postgresql
    hostname: postgresql
    image: postgres
    environment:
      POSTGRES_PASSWORD: "jungle123"
      POSTGRES_USER: "jungle"
      POSTGRES_DB: "jungle"
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data


volumes:
  postgresql_data: