# Generated by Django 4.0.4 on 2022-05-12 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_articles_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='body',
            field=models.CharField(max_length=10000),
        ),
    ]
